// @flow

export const API_CALL_FAILURE: "API_CALL_FAILURE" = 'API_CALL_FAILURE';
export const API_CALL_STARTED_SENDING: "API_CALL_STARTED_SENDING" =
  'API_CALL_STARTED_SENDING';
export const API_CALL_FINISHED_SENDING: "API_CALL_FINISHED_SENDING" =
  'API_CALL_FINISHED_SENDING';
export const API_CALL_SUCCESS: "API_CALL_SUCCESS" = 'API_CALL_SUCCESS';
export const RSAA: "RSAA" = 'RSAA';
