// @flow

import { RSAA as RSAAImport } from '../middleware/RSAA/actionTypes';

export const DEFAULT: "DEFAULT" = 'DEFAULT';
export const API_CALL_FAILURE: "API_CALL_FAILURE" = 'API_CALL_FAILURE';
export const RSAA = RSAAImport;
export const SET_SAMPLEPROP: "SET_SAMPLEPROP" = 'SET_SAMPLEPROP';
export const STARTED_FETCHING_USERS: "STARTED_FETCHING_USERS" =
  'STARTED_FETCHING_USERS';
export const FINISHED_FETCHING_USERS: "FINISHED_FETCHING_USERS" =
  'FINISHED_FETCHING_USERS';
export const UPDATE_USERS_WITH_FETCHED: "UPDATE_USERS_WITH_FETCHED" =
  'UPDATE_USERS_WITH_FETCHED';
export const EDIT_USER: "EDIT_USER" = 'EDIT_USER';
